--
-- PostgreSQL database dump
--

-- Dumped from database version 11.18
-- Dumped by pg_dump version 11.18

-- Started on 2023-03-09 10:37:41

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE library;
--
-- TOC entry 2833 (class 1262 OID 16506)
-- Name: library; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE library WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'Russian_Russia.1251' LC_CTYPE = 'Russian_Russia.1251';


ALTER DATABASE library OWNER TO postgres;

\connect library

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO postgres;

--
-- TOC entry 2834 (class 0 OID 0)
-- Dependencies: 3
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_with_oids = false;

--
-- TOC entry 199 (class 1259 OID 16518)
-- Name: books; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.books (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    author character varying(50),
    releaseyear integer,
    owner bigint,
    is_del boolean DEFAULT false NOT NULL
);


ALTER TABLE public.books OWNER TO postgres;

--
-- TOC entry 198 (class 1259 OID 16516)
-- Name: books_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.books ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.books_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 197 (class 1259 OID 16509)
-- Name: persons; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.persons (
    id bigint NOT NULL,
    fio character varying(100) NOT NULL,
    birthyear integer,
    is_del boolean DEFAULT false NOT NULL
);


ALTER TABLE public.persons OWNER TO postgres;

--
-- TOC entry 196 (class 1259 OID 16507)
-- Name: persons_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.persons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.persons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 200 (class 1259 OID 24705)
-- Name: persons_view; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.persons_view AS
 SELECT p.id,
    p.fio,
    p.birthyear,
    bf.cnt
   FROM (public.persons p
     LEFT JOIN ( SELECT b.owner,
            count(b.id) AS cnt
           FROM public.books b
          WHERE (b.is_del = false)
          GROUP BY b.owner) bf ON ((p.id = bf.owner)))
  WHERE (p.is_del = false);


ALTER TABLE public.persons_view OWNER TO postgres;

--
-- TOC entry 2827 (class 0 OID 16518)
-- Dependencies: 199
-- Data for Name: books; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.books VALUES (2, '«На службе зла»', 'Р. Гэлбрейт', 1995, 1, false);
INSERT INTO public.books VALUES (4, '«Код да Винчи»', 'Д. Браун', 2006, 1, false);
INSERT INTO public.books VALUES (5, '«Старик и море»', 'Э. Хэмингуэй', 2003, NULL, false);
INSERT INTO public.books VALUES (3, '«Таинственный противник»', 'А. Кристи', 1988, 2, false);
INSERT INTO public.books VALUES (1, '«Тайна синего экспресса»', 'А. Кристи', 2001, NULL, false);


--
-- TOC entry 2825 (class 0 OID 16509)
-- Dependencies: 197
-- Data for Name: persons; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.persons VALUES (1, 'Житников Владимир Васильевич', 1971, false);
INSERT INTO public.persons VALUES (6, 'Федоров Мирон Янович', 1968, false);
INSERT INTO public.persons VALUES (2, 'Петров Николай Сергеевич', 1991, false);
INSERT INTO public.persons VALUES (3, 'Спиридонов Всеволод Григорьевич', 1946, false);


--
-- TOC entry 2835 (class 0 OID 0)
-- Dependencies: 198
-- Name: books_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.books_id_seq', 5, true);


--
-- TOC entry 2836 (class 0 OID 0)
-- Dependencies: 196
-- Name: persons_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.persons_id_seq', 7, true);


--
-- TOC entry 2700 (class 2606 OID 16522)
-- Name: books books_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.books
    ADD CONSTRAINT books_pkey PRIMARY KEY (id);


--
-- TOC entry 2698 (class 2606 OID 16513)
-- Name: persons persons_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.persons
    ADD CONSTRAINT persons_pkey PRIMARY KEY (id);


--
-- TOC entry 2701 (class 2606 OID 24699)
-- Name: books books_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.books
    ADD CONSTRAINT books_fk FOREIGN KEY (owner) REFERENCES public.persons(id) ON UPDATE SET NULL ON DELETE RESTRICT;


-- Completed on 2023-03-09 10:37:41

--
-- PostgreSQL database dump complete
--

